[book]
title = "ISO-TP Documentation"
language = "en"

[output.html]
default-theme = "light"
git-repository-url = "https://github.com/espressif/idf-extra-components/tree/master/esp_isotp"
edit-url-template = "https://github.com/espressif/idf-extra-components/edit/master/esp_isotp/docs/{path}"